export const courses = [
  {
    id: 1,
    name: "Анна Иванова",
    img: "/assets/img/course/course-thumb-01.jpg",
    icon: "/assets/img/icon/course-avata-01.png",
    title: "Полный лагерь веб-разработки 2022 года",
    cls_text: "35 Classes",
    st_text: "291 Students",
    start_text: "4.7",
    course_title: "Design",
    course_link: "/course/1",
    course_name: "Development",
    course_price: "29.99",
    duration: "16 hours",
    students: 105,
    quizess: 6,
    lesson: 36,
    level: "Beginner",
    language: "English",
    description:
      "Этот курс представляет собой интенсивное обучение веб-разработке, актуальное на 2022 год. Вы узнаете основы HTML, CSS и JavaScript, а также научитесь создавать динамические веб-сайты и веб-приложения. Преподаватели поделятся с вами свежими тенденциями и лучшими практиками в этой быстро развивающейся сфере.",
  },
  {
    id: 2,
    name: "Максим Петров",
    img: "/assets/img/course/course-thumb-02.jpg",
    icon: "/assets/img/icon/course-avata-02.png",
    title: "Полный веб-дизайн от Figma до Webflow",
    cls_text: "30 Classes",
    st_text: "245 Students",
    start_text: "4.8",
    course_title: "Design",
    course_link: "/course/2",
    course_name: "Design",
    course_price: "34.99",
    duration: "20 hours",
    students: 120,
    quizess: 5,
    lesson: 40,
    level: "Intermediate",
    language: "English",
    description:
      "Этот курс предназначен для тех, кто хочет стать профессионалом в веб-дизайне. Вы изучите основы дизайна, работу с графическими инструментами, создание макетов в Figma и их превращение в реальные веб-сайты с использованием платформы Webflow.",
  },
  {
    id: 3,
    name: "Елена Смирнова",
    img: "/assets/img/course/course-thumb-03.jpg",
    icon: "/assets/img/icon/course-avata-03.png",
    title: "SEO: разметка структурированных данных для веб-мастеров",
    cls_text: "25 Classes",
    st_text: "180 Students",
    start_text: "4.6",
    course_title: "Digital Marketing",
    course_link: "/course/3",
    course_name: "SEO",
    course_price: "24.99",
    duration: "12 hours",
    students: 90,
    quizess: 4,
    lesson: 30,
    level: "Advanced",
    language: "Russian",
    description:
      "Этот курс предоставит вам глубокое понимание SEO и разметки структурированных данных. Вы узнаете, как улучшить видимость вашего веб-сайта в поисковых системах, оптимизировать контент и применять разметку для улучшения понимания контента поисковыми системами.",
  },
  {
    id: 4,
    name: "Алексей Кузнецов",
    img: "/assets/img/course/course-thumb-04.jpg",
    icon: "/assets/img/icon/course-avata-04.png",
    title: "Полный веб-дизайн от Figma Freelancing",
    cls_text: "28 Classes",
    st_text: "210 Students",
    start_text: "4.9",
    course_title: "Design",
    course_link: "/course/4",
    course_name: "Design",
    course_price: "39.99",
    duration: "18 hours",
    students: 95,
    quizess: 7,
    lesson: 35,
    level: "Intermediate",
    language: "English",
    description:
      "Этот курс ориентирован на тех, кто хочет начать фриланс-карьеру в веб-дизайне. Вы научитесь создавать креативные макеты в Figma, работать с клиентами, понимать их потребности и требования, а также эффективно управлять проектами.",
  },
  {
    id: 5,
    name: "Ольга Васильева",
    img: "/assets/img/course/course-thumb-05.jpg",
    icon: "/assets/img/icon/course-avata-05.png",
    title: "Основы программирования на Python",
    cls_text: "40 Classes",
    st_text: "320 Students",
    start_text: "4.5",
    course_title: "Development",
    course_link: "/course/5",
    course_name: "Python",
    course_price: "19.99",
    duration: "22 hours",
    students: 150,
    quizess: 8,
    lesson: 45,
    level: "Beginner",
    language: "Russian",
    description:
      "Этот курс предоставляет базовые знания программирования на Python. Вы изучите синтаксис языка, основные структуры данных и научитесь создавать простые программы и скрипты.",
  },
  {
    id: 6,
    name: "Дмитрий Соколов",
    img: "/assets/img/course/course-thumb-06.jpg",
    icon: "/assets/img/icon/course-avata-06.png",
    title: "Разработка мобильных приложений на Android",
    cls_text: "32 Classes",
    st_text: "280 Students",
    start_text: "4.7",
    course_title: "Development",
    course_link: "/course/6",
    course_name: "Android",
    course_price: "29.99",
    duration: "20 hours",
    students: 110,
    quizess: 6,
    lesson: 38,
    level: "Intermediate",
    language: "English",
    description:
      "Этот курс научит вас разрабатывать мобильные приложения на платформе Android. Вы изучите язык программирования Kotlin, создание пользовательских интерфейсов и взаимодействие с устройствами.",
  },
  {
    id: 8,
    name: "Игорь Попов",
    img: "/assets/img/course/course-thumb-08.jpg",
    icon: "/assets/img/icon/course-avata-08.png",
    title: "Анализ данных с использованием Python",
    cls_text: "38 Classes",
    st_text: "310 Students",
    start_text: "4.8",
    course_title: "Data Science",
    course_link: "/course/7",
    course_name: "Python for Data Analysis",
    course_price: "39.99",
    duration: "24 hours",
    students: 130,
    quizess: 7,
    lesson: 42,
    level: "Intermediate",
    language: "English",
    description:
      "Этот курс научит вас анализу данных с помощью языка программирования Python. Вы изучите основы работы с данными, визуализацию и применение аналитических методов.",
  },
  {
    id: 9,
    name: "Татьяна Федорова",
    img: "/assets/img/course/course-thumb-09.jpg",
    icon: "/assets/img/icon/course-avata-09.png",
    title: "Искусственный интеллект и машинное обучение",
    cls_text: "36 Classes",
    st_text: "270 Students",
    start_text: "4.7",
    course_title: "Data Science",
    course_link: "/course/8",
    course_name: "AI & Machine Learning",
    course_price: "34.99",
    duration: "22 hours",
    students: 120,
    quizess: 6,
    lesson: 40,
    level: "Advanced",
    language: "English",
    description:
      "Этот курс предоставит вам знания о искусственном интеллекте и машинном обучении. Вы изучите основные алгоритмы и методы, а также научитесь применять их на практике.",
  },
  {
    id: 10,
    name: "Андрей Павлов",
    img: "/assets/img/course/course-thumb-10.jpg",
    icon: "/assets/img/icon/course-avata-10.png",
    title: "Введение в кибербезопасность",
    cls_text: "20 Classes",
    st_text: "150 Students",
    start_text: "4.6",
    course_title: "Cybersecurity",
    course_link: "/course/9",
    course_name: "Introduction to Cybersecurity",
    course_price: "29.99",
    duration: "10 hours",
    students: 70,
    quizess: 4,
    lesson: 28,
    level: "Beginner",
    language: "English",
    description:
      "Этот курс представляет введение в основы кибербезопасности. Вы узнаете о методах защиты данных и информационных систем от кибератак и угроз.",
  },
];
