import Head from "next/head";

type SeoType = {
  pageTitle: string;
  description?: string;
};

const SEO = ({
  pageTitle,
  description = "Generated by create next app",
}: SeoType) => (
  <>
    <Head>
      <title>
        {pageTitle &&
          `${pageTitle} - Online Courses & Education React Next js Template`}
      </title>
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      <meta name="description" content={description} />
      <meta name="robots" content="noindex, follow" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
      />
      <link rel="icon" href="/favicon.png" />
    </Head>
  </>
);

export default SEO;
